runtime: python27
api_version: 1
threadsafe: true

handlers:
-  url: /stylesheets
   static_dir: stylesheets

-  url: /images
   static_dir: static/images

-  url: /.*
   script: main.app
   
